services:
  backend:
    build: .
    image: wiclive-backend
    container_name: wiclive-backend
    restart: unless-stopped
    expose:
      - "3243"
    networks:
      - wicgate-net
    volumes:
      - maps:/app/maps
      - uploads:/app/uploads
      - ./files:/app/files
      - ./keys.json:/app/keys.json:ro
      - ./_data.json:/app/_data.json
      # Mount SSL certificates for HTTPS
      # - /path/to/ssl/key.pem:/app/ssl/key.pem:ro
      # - /path/to/ssl/cert.pem:/app/ssl/cert.pem:ro
    environment:
      - ENV_DEVELOPMENT=false
      # - SSL_DIR=/app/ssl

networks:
  wicgate-net:
    external: true

volumes:
  maps:
  uploads:
